quiet: true

skip-check:
  - CKV_AWS_158   # Ensure that CloudWatch Log Group is encrypted by KMS.
  - CKV_AWS_338   # Ensure CloudWatch log groups retains logs for at least 1 year (7 days is sufficient for handson)
  - CKV_AWS_115   # Ensure that AWS Lambda function is configured for function-level concurrent execution limit (not needed for handson)
  - CKV_AWS_272   # Ensure AWS Lambda function is configured to validate code-signing (not needed for handson)
  - CKV_AWS_173   # Check encryption settings for Lambda environmental variable (not needed for handson)
  - CKV_AWS_50    # X-Ray tracing is enabled for Lambda (not required per specification)
  - CKV_AWS_116   # Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ) (not needed for handson)
  - CKV_AWS_117   # Ensure that AWS Lambda function is configured inside a VPC (explicitly prohibited in specification)
  - CKV_AWS_258   # Ensure that Lambda function URLs AuthType is not None (public access is required per specification)
